from __future__ import annotations

# MG_RESUME_PREPROCESSING_V2

from ..checkpoint import (
    CheckpointJournal,
    file_identity,
    fingerprint,
    source_digest,
)

from ..io.preflight import (
    canonicalize_raw_storage_2d,
    preflight_metadata_input,
)

from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
import tifffile

from ..metadata.files import (
    NomenclatureScan,
)

from .config import (
    PreprocessingConfig,
)
from .processor import (
    process_image,
)
from .presets import (
    display_name_for_preset,
)


@dataclass
class PreprocessingResult:
    """
    Result produced by the Preprocessing stage.

    prepared_paths
        Images ready for the Segmentation stage.

        raw:
            Paths to binary images generated by Preprocessing.

        binary / labels:
            Paths to the original supplied images because no image
            preprocessing is required.
    """

    prepared_paths: list[Path]
    input_mode: str
    skipped_others: int
    processed_count: int


def _load_image(
    path: Path,
) -> np.ndarray:
    """
    Load one supported microscopy image without changing its scale.
    """

    suffix = path.suffix.lower()

    if suffix in {
        ".tif",
        ".tiff",
    }:
        image = tifffile.imread(
            str(path)
        )

    elif suffix in {
        ".png",
        ".jpg",
        ".jpeg",
    }:
        image = cv2.imread(
            str(path),
            cv2.IMREAD_UNCHANGED,
        )

        if image is None:
            raise ValueError(
                f"Could not load image: {path}"
            )

        if image.ndim == 3:
            image = cv2.cvtColor(
                image,
                cv2.COLOR_BGR2GRAY,
            )

    else:
        raise ValueError(
            f"Unsupported image format: {path.suffix}"
        )

    return np.asarray(
        image
    )


def _save_tiff(
    path: Path,
    image: np.ndarray,
) -> None:
    """Write one TIFF to a temporary sibling and atomically replace."""

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = path.with_name(
        f"{path.stem}.tmp{path.suffix}"
    )

    if temporary.exists():
        temporary.unlink()

    try:
        tifffile.imwrite(
            str(temporary),
            image,
        )
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


def print_preprocessing_summary(
    config: PreprocessingConfig,
) -> None:

    separator = "=" * 72

    print()
    print(separator)
    print("PREPROCESSING")
    print(separator)
    print()

    mode = (
        config.effective_input_mode
    )

    print(
        "Image geometry:      "
        f"{config.effective_spatial_dimension.upper()}"
    )

    print(
        f"Input mode:          {mode}"
    )

    if mode == "binary":
        print(
            "Image filtering:     None"
        )
        print(
            "Source images:       Used directly"
        )
        return

    if mode == "labels":
        print(
            "Image filtering:     None"
        )
        print(
            "Source labels:       Used directly"
        )
        return

    print(
        f"Preset:              "
        f"{display_name_for_preset(config.effective_preset)}"
    )

    print(
        f"Save intermediate:   "
        f"{config.effective_save_intermediate}"
    )

    print()
    print("Sequence:")
    print("-" * 72)

    for index, operation in enumerate(
        config.sequence,
        start=1,
    ):
        print(
            f"{index:02d}. {operation}"
        )


def run_preprocessing(
    input_dir: str | Path,
    output_dir: str | Path,
    metadata_scan: NomenclatureScan,
    config: PreprocessingConfig,
    resume: bool = False,
) -> PreprocessingResult:
    """
    Prepare every Metadata-recognized image for Segmentation.

    raw
        Apply the configured preprocessing preset and save its binary
        output under Preprocessing/Binary.

    binary
        No image transformation or duplicate file is produced.
        The source image is passed directly to Segmentation.

    labels
        No image transformation or duplicate file is produced.
        The source label image is passed directly to Segmentation.

    Raw source files are never modified.
    """
    preflight_metadata_input(
        input_dir=input_dir,
        metadata_scan=metadata_scan,
        preprocessing_config=config,
    )

    input_dir = Path(
        input_dir
    )

    output_dir = Path(
        output_dir
    )

    preprocessing_dir = (
        output_dir
        / "Preprocessing"
    )

    preprocessing_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print_preprocessing_summary(
        config
    )

    mode = (
        config.effective_input_mode
    )

    prepared_paths: list[Path] = []

    recognized = (
        metadata_scan.recognized
    )

    total = len(
        recognized
    )

    # ==================================================================
    # BINARY / LABELS
    #
    # Nothing needs to be copied or transformed.
    # ==================================================================

    if mode in {
        "binary",
        "labels",
    }:

        for index, interpretation in enumerate(
            recognized,
            start=1,
        ):

            source_path = (
                input_dir
                / interpretation.original_filename
            )

            print(
                f"[{index}/{total}] "
                f"{interpretation.original_filename}"
            )

            prepared_paths.append(
                source_path
            )

    # ==================================================================
    # RAW
    # ==================================================================

    else:

        binary_dir = (
            preprocessing_dir
            / "Binary"
        )

        binary_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        stage_signature = fingerprint(
            "preprocessing_resume_v2",
            config,
            source_digest(Path(__file__)),
            source_digest(Path(__file__).with_name("processor.py")),
            source_digest(Path(__file__).with_name("presets.py")),
            source_digest(Path(__file__).with_name("filters.py")),
            source_digest(Path(__file__).with_name("filter_parameters.py")),
        )
        journal = CheckpointJournal(
            output_dir=output_dir,
            stage="preprocessing",
            resume=resume,
            stage_signature=stage_signature,
        )

        for index, interpretation in enumerate(
            recognized,
            start=1,
        ):

            source_path = (
                input_dir
                / interpretation.original_filename
            )

            canonical_filename = (
                interpretation.canonical_filename
            )

            if canonical_filename is None:
                continue

            canonical_stem = Path(
                canonical_filename
            ).stem

            output_path = (
                binary_dir
                / f"{canonical_stem}.tif"
            )

            expected_outputs = [output_path]
            if config.effective_save_intermediate:
                for step_index, operation in enumerate(config.sequence, start=1):
                    expected_outputs.append(
                        preprocessing_dir
                        / "Intermediate"
                        / f"{step_index:02d}_{operation}"
                        / f"{canonical_stem}.tif"
                    )

            item_signature = fingerprint(
                stage_signature,
                file_identity(source_path),
                canonical_filename,
            )

            if journal.reusable_record(
                item_id=canonical_stem,
                item_signature=item_signature,
                outputs=expected_outputs,
            ) is not None:
                print(
                    f"[{index}/{total}] RESUME "
                    f"{interpretation.original_filename}"
                )
                print(f"    -> {output_path.name}")
                prepared_paths.append(output_path)
                continue

            print(
                f"[{index}/{total}] "
                f"{interpretation.original_filename}"
            )

            print(
                f"    -> {output_path.name}"
            )

            image = _load_image(
                source_path
            )

            # ----------------------------------------------------------
            # DECLARED BIOLOGICAL 2D
            #
            # Extra raw storage planes are maximum-intensity projected
            # BEFORE operation 01.
            # ----------------------------------------------------------

            image = canonicalize_raw_storage_2d(
                image,
                source_name=source_path.name,
            )

            if (
                config.effective_save_intermediate
            ):

                binary, intermediate = (
                    process_image(
                        image=image,
                        config=config,
                        collect_intermediate=True,
                    )
                )

                for step_index, (
                    operation,
                    step_image,
                ) in enumerate(
                    intermediate,
                    start=1,
                ):

                    intermediate_dir = (
                        preprocessing_dir
                        / "Intermediate"
                        / (
                            f"{step_index:02d}_"
                            f"{operation}"
                        )
                    )

                    intermediate_path = (
                        intermediate_dir
                        / f"{canonical_stem}.tif"
                    )

                    _save_tiff(
                        intermediate_path,
                        step_image,
                    )

            else:

                binary = process_image(
                    image=image,
                    config=config,
                    collect_intermediate=False,
                )

            _save_tiff(
                output_path,
                binary,
            )

            prepared_paths.append(
                output_path
            )

            journal.commit(
                item_id=canonical_stem,
                item_signature=item_signature,
                outputs=expected_outputs,
            )

    print()
    print("=" * 72)
    print("PREPROCESSING COMPLETE")
    print("=" * 72)
    print()

    print(
        "Prepared images:  ",
        len(
            prepared_paths
        ),
    )

    print(
        "Skipped Others:   ",
        metadata_scan.others_count,
    )

    if mode in {
        "binary",
        "labels",
    }:
        print(
            "Copies created:    0"
        )

    else:
        print(
            "Binary directory: ",
            preprocessing_dir
            / "Binary",
        )

    print()

    return PreprocessingResult(
        prepared_paths=prepared_paths,
        input_mode=mode,
        skipped_others=(
            metadata_scan.others_count
        ),
        processed_count=len(
            prepared_paths
        ),
    )
